### ISSUE TITLE
Can't use Pulumi output values as args

### ISSUE THREAD

**Issue by seunggs** [pulumi/pulumi-kubernetes-cert-manager#1]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Errors out while creating the cert-manager resource with Pulumi output value as args:

```
error: Error: failed to register new resource cert-manager [kubernetes-cert-manager:index:CertManager]: 2 UNKNOWN: setting args: copying input "helmOptions": provider.CertManagerArgs.HelmOptions is typed as *helm.ReleaseType but must be a type that implements pulumi.Input or pulumi.Output for input with dependencies
```

### Steps to reproduce
Creating the cert-manager resource using the below code:

```
const certManager = new certmanager.CertManager("cert-manager", {
      installCRDs: true,
      helmOptions: {
        namespace: certManagerNamespaceName,
        values: {
          serviceAccount: {
            annotations: {
              'eks.amazonaws.com/role-arn': certManagerRole.arn,
            }
          },
          securityContext: {
            fsGroup: 1001
          },
        }
      },
    }, { provider: k8sProvider })
```

Errors out due to the Pulumi output value `certManagerRole.arn`.

Also tried using serviceAccount and secuirtyContext args directly rather than inside helmOptions.values, but same error for all args.

Expected: 
Ideally, should be able to create the resource with arg values of Pulumi outputs.

Actual: 
Error creating resource

**Comment by seunggs** [comment]
Any update on this?

**Comment by pcuci** [comment]
Same issue :-)

> Works fine when hardcoding a string value.

Confirming this workaround.

Though, I'd rather use the dynamically generated namespace name by Pulumi rather than a static name, so a fix here would be nice.

**Comment by EronWright** [comment]
Seems like the issue was resolved, we simply need a new release of this provider to effectively use it.

**Comment by Tungsten78** [comment]
Still seeing this issue in v0.1.1.   Similar to #133 but specific to using an output for the namespace args.

cc: @aureq

**Comment by rshade** [comment]
@Tungsten78 Can you open a new issue and include your code?

**Comment by Tungsten78** [comment]
> [@Tungsten78](https://github.com/Tungsten78) Can you open a new issue and include your code?

See #306
